### ISSUE TITLE
Add Notification on Wordpress Dashboard

### ISSUE THREAD

**Issue by brainwithE** [NateWr/restaurant-reservations#104]
I am currently creating a reservation system using your plugin in Wordpress. Is there a way that I could add a notification beside the Booking item in the dashboard menu?
I would like to output the total count of new pending reservation.

Thank you for your response.

**Comment by NateWr** [comment]
This would be a great feature to add. Are you comfortable working with PHP code and able to issue a pull request with this feature? If so, here's what would need to happen:

1. Hook into the `rtb_insert_booking` and `rtb_update_booking` actions [here](https://github.com/NateWr/restaurant-reservations/blob/master/includes/Booking.class.php#L171) which fire every time a booking is added or updated. There you'll want to get the count of pending bookings and save it as a site option using `update_option()`.

2. Hook into `admin_menu` to update the menu label with the current count bubble, as shown in [this sample](https://www.skyverge.com/blog/add-admin-menu-notification-bubble/).

This would ensure there's minimal impact on performance and the count stays accurate.

**Comment by brainwithE** [comment]
I'm not really comfortable changing plugin's codes, but I would like to try. Also is there a way that I want to show the summary or the total count of pending/confirmed/cancelled reservations per day in the wordpress dashboard's page? Thanks

**Comment by brainwithE** [comment]
Hi Nate,

Is this correct? Thanks

public function insert_booking() {
$count = 0;
// Check if this request has already been processed. If multiple forms
// exist on the same page, this prevents a single submission from
// being added twice.
if ( $this->request_processed === true ) {
return true;
}

$this->request_processed = true;

if ( empty( $this->ID ) ) {
$action = 'insert';
} else {
$action = 'update';
}

$this->validate_submission();
if ( $this->is_valid_submission() === false ) {
return false;
}

if ( $this->insert_post_data() === false ) {
return false;
} else {
$this->request_inserted = true;
}

do_action( 'rtb_' . $action . '_booking', $this );

if ($action = 'insert') {
update_option( 'pending_reservation_count', $count++ );
}

return true;
}

**Comment by NateWr** [comment]
No, that's not quite going to work. It will always set the value to 1. I'd also like to use the hooks rather than put that logic directly into that function.

I'll try to work up a feature like this before too long, but I'm going on holiday soon so it's not likely to happen until at least late April.

**Comment by NateWr** [comment]
@brainwithE I implemented this in the commit above. You can take a look if you want to know how I went about it. This feature will go out with the next update, probably later today.
