### ISSUE TITLE
Booking form and WPML

### ISSUE THREAD

**Issue by Ciao121** [NateWr/restaurant-reservations#105]
Hi,
I can't find any way to translate the booking form to another language.
On the second language page I do not get the form.

Any help?
Thank you!!!

**Comment by NateWr** [comment]
HI @Ciao121,

I'm not very familiar with WPML but I know that some customers have managed to do it. The key is to translate the Booking Page setting. I believe you use something like "String Translation" for this in WPML. If you search the WPML forums you might find what you're looking for.

**Comment by NateWr** [comment]
Were you able to resolve this? Also, I've filed an issue to work on the WPML integration to send emails. You can follow that here:

https://github.com/NateWr/restaurant-reservations/issues/108
