### ISSUE TITLE
WPML support

### ISSUE THREAD

**Issue by dlakomski** [NateWr/restaurant-reservations#11]
Is there any possibilities to make this plugin compatibile with the WPML translations? At the moment there is no way to translate settings like: "New Request Email Subject", "New Request Email" etc.

**Comment by NateWr** [comment]
Hi dlaskomski,

I am in the final stages of WPML's Go Global program. I'm basically waiting on a sign-off from them that everything is good to go. The latest version of master includes everything but the wpml-config.xml file.

**Comment by NateWr** [comment]
Woops! mis-clicked before finishing the thought.

Basically all the changes I've made to get it WPML compatible are in the master branch and will go out with the next release, except the wpml-config.xml file. You can copy/paste this into the root directory of the plugin.

	<wpml-config>
		<admin-texts>
			<key name="rtb-settings">
				<key name="booking-page" />
				<key name="success-message" />
				<key name="date-format" />
				<key name="time-format" />
				<key name="i8n" />
				<key name="reply-to-name" />
				<key name="subject-booking-admin" />
				<key name="template-booking-admin" />
				<key name="subject-booking-user" />
				<key name="template-booking-user" />
				<key name="subject-confirmed-user" />
				<key name="template-confirmed-user" />
				<key name="subject-rejected-user" />
				<key name="template-rejected-user" />
			</key>
		</admin-texts>
	</wpml-config>

Hopefully I'll get the final sign-off soon. Food and Drink Menu has already been through the process and my other two plugins are going through the same process now.

**Comment by NateWr** [comment]
I've finally included the `wpml-config.xml` file. This doesn't have final approval from the WMPL folks, but things have slowed down on that front and this appears to have worked for several people.

Added in 9ada7610a3d0b42dc2afefd8a655c27183f8b060.
