### ISSUE TITLE
Migrate translations to wordpress.org

### ISSUE THREAD

**Issue by davidperezgar** [NateWr/restaurant-reservations#111]
In order to collaborate and translate independently of the language.

Congratulations with the plugin.

Thanks!

**Comment by NateWr** [comment]
Hi @davidperezgar,

I'd be happy to do so, but I need a committed editor for any language I remove from those I distribute with the plugin. You can see the status of translations here:

https://translate.wordpress.org/projects/wp-plugins/restaurant-reservations

If you're willing to take responsibility for a language, you can begin translating there. When you're done, let me know your wordpress.org username and I can request that you be made an editor for that language. Someone from the polylang team then checks the quality and will grant you permission to approve translations for that language.

**Comment by davidperezgar** [comment]
Ok, I will see it to confirm strings in spanish.
