### ISSUE TITLE
Little mispelling in includes/AdminBookings.class.php

### ISSUE THREAD

**Issue by mumbomedia** [NateWr/restaurant-reservations#112]
Hello Mr. Wright

today I found a little issue, which doesn't cause trouble if the plugin isn't customize.
but as you know we did it and therefore I have found this.

On line 22 of "includes/AdminBookings.class.php" the public variable is named "$booking_table" but in function "show_admin_bookings_page" on line 77 you're referring "$this->booking**s**_table".
So on line 22 there is a "s" missing. Therefore the class has an unused variable which consume memory .
So I would appreticate if you could change it asap.

Kind regards

mumbomedia

**Comment by NateWr** [comment]
Good catch @mumbomedia! :thumbsup:
