### ISSUE TITLE
Reservations just for Mail-Notification (not in WP-Database)

### ISSUE THREAD

**Issue by pss77** [NateWr/restaurant-reservations#120]
Hello NateWr,

i had installed the Reservations-Plugin, great tool, thanks!

I only need the Reservation-Plugin for Booking-Request by E-Mail - the rest i handle manually!
(I dont need the Request in the WP-Database).

Can you give me an advice or write a little plugin to stop or pass over the public function "insert_post_data()" in the file "Booking.class.php".  I am not such a PHP-Profi :)

You know, what I mean?

Greetings Pete

**Comment by NateWr** [comment]
Hi Pete, sorry for the delay in responding. I'm just seeing this now. I believe you reached out through another channel and we discussed this there. In short, it's just not really possible to get the functionality of the plugin without writing to the database. Even the email notifications are tied to the database writing operations, so you'd basically need to rewrite major chunks of the plugin.
