### ISSUE TITLE
Changing status the second time not sending email to client

### ISSUE THREAD

**Issue by BaltasarParreira** [NateWr/restaurant-reservations#121]
If I change the status again for a reservation already processed even clicking the send notification box the customer does not receive any email.

**Comment by NateWr** [comment]
Hi @BaltasarParreira,

Emails are only send for particular status transitions: from pending-to-confirmed or pending-to-closed. These match the email templates set up in Bookings > Settings > Notifications.

There are no emails configured to send when transitioning from confirmed-to-closed or any other transition.

**Comment by BaltasarParreira** [comment]
Ok I understand, thanks.
