### ISSUE TITLE
WooCommerce for food ordering

### ISSUE THREAD

**Issue by bitsavvy** [NateWr/restaurant-reservations#125]
HI there,

Would it be possible to integrate WooCommerce for food ordering? Could you give us a basic idea of what would be required to write an add-on for this or via hooks etc.

Kind regards 
Francois Wessels

**Comment by NateWr** [comment]
Hi @bitsavvy,

It would be possible, but in most cases I recommend people just work from the WooCommerce end of things. It will be easier to style a WooCommerce shop to look like a menu than it will be to integrate proper eCommerce checkout and shopping cart features into the Restaurant Reservations booking form.

I'm not that familiar with WooCommerce so I can't be very helpful. The developer documentation includes some helpful snippets and guides on modifying booking form fields and such:

http://doc.themeofthecrop.com/plugins/restaurant-reservations/developer/
