### ISSUE TITLE
Holiday period is closed automatically

### ISSUE THREAD

**Issue by carlosromanxyz** [NateWr/restaurant-reservations#127]
Hello

My client's restaurant has no holiday period, since it opened recently and has not thought about closing since it is in a tourist area.

Adding the dates one by one for more than 60 days (considering that it opens from Monday to Saturday) is complicated

I consider it convenient not to automate this functionality and give the user the possibility to activate it.

Please check my config

![fireshot capture 43 - ajustes invinum wordpress_ - https___invinum cl_wp-admin_admin php](https://user-images.githubusercontent.com/20117120/34594589-bec56094-f1b0-11e7-8562-aee48617e51b.png)

**Comment by NateWr** [comment]
I'm sorry, it's not clear to me what you're asking. Is this a feature request?

**Comment by carlosromanxyz** [comment]
No, isn't a request.

Apparently your plugin not work in January/February (Holiday period). Why?

**Comment by NateWr** [comment]
Hi @carlosromanxyz,

I haven't heard of anyone else having that problem. It sounds like it may be unique to your setup. To diagnose, you can try to deactivate all other plugins and switch to a default theme to see if there is a conflict somewhere. 

But it doesn't appear to be a general issue. There are over 20,000 sites using the plugin, so if it just stopped working in Jan/Feb I would have complaints.
