### ISSUE TITLE
i18n for current_time

### ISSUE THREAD

**Issue by inbaz** [NateWr/restaurant-reservations#130]
Hey, I'm trying out your plugin for a customer and it's really nice. However I found a small thing that can be improved:

https://github.com/NateWr/restaurant-reservations/blob/master/includes/Notification.class.php#L93

When a date_string in Wordpress is chosen to display 11. March 2018, this line above will keep this date in english.

https://codex.wordpress.org/Function_Reference/date_i18n

Wordpress already has a date_i18n function included. I just changed date to date_i18n and I'm getting nice internationalized date strings now. :)

Maybe this is an enhancement you want to include in one of your next versions of this plugin.

Cheers
Andi

**Comment by NateWr** [comment]
Thanks @inbaz! I wasn't aware of the `date_i18n` function. This should be easy to get into the next version. Are you able to issue a pull request with this change?

**Comment by inbaz** [comment]
The pull request should be there. Please have a look.

**Comment by NateWr** [comment]
Merged. Thanks!
