### ISSUE TITLE
Confirmation email, send in original booking page language

### ISSUE THREAD

**Issue by Tha14** [NateWr/restaurant-reservations#143]
Hello,
Kinda customized my version of this plugin so this doesn't have to be an official update, but how would I go about sending the confirmation/rejection email in the language based on the page the user used to book? For me it's not working right now as I understand that it's not a plugin that is supposed to completely work with multiple languages.
Thanks for this awesome plugin :D

**Comment by JeePeeNL** [comment]
I would also like to see that!

**Comment by Tha14** [comment]
> I would also like to see that!

I guess I could write a function that saves the page language when you use the booking form and then from the backend it automatically sends the email with the language template based on that option.
