### ISSUE TITLE
Date Picker grayed out...

### ISSUE THREAD

**Issue by 1quicksi** [NateWr/restaurant-reservations#146]
I had the site up and running with no issues for my client. For some reason now the date picker has all the dates grayed out. I can choose a time and all the other fields but I can not select a date nor can I advanced the calendar to the net or previous month.

I have tried to disable all the plugins as well as going back to a default WP theme, but the same issue is happening. I have tried to deactivate and delete the plugin. But when I re-upload the files and activate the data is still there, so it is not really being fully removed? I looked in phpmyadmin (danger but desperate) but did not see anything related to the plugin…

Of course this is happening the day the site is supposed to go live…

The page I need help with: http://www.yourminiescape.com/reservations/

**Comment by JeePeeNL** [comment]
What does your booking schedule look like in Bookings » Settings » [Booking Schedule]?

**Comment by JeePeeNL** [comment]
I think it is the early booking setting. It says that you can make a reservation from 1 day in advance. So today it means you an only make a reservation for Monday. You probably don't want to restrict that, who cares if someone books a year ahead?

**Comment by 1quicksi** [comment]
Bingo, that was it.  Thank you for taking the time out of your day to help!!!

**Comment by NateWr** [comment]
:+1: thanks @JeePeeNL!
