### ISSUE TITLE
Replace German translation

### ISSUE THREAD

**Issue by NateWr** [NateWr/restaurant-reservations#16]
Apparently the German translation that shipped with v1.3 is slang or a dialect not common in Germany. Roland Stumpp submitted an improved version.

**Comment by michaelbeil** [comment]
that's strange. glad Roland has got a new one in. do you need a .mo of it as well?

**Comment by NateWr** [comment]
Fixed in 64fb522f055ab54d85a883edb26a52352862f346.

Yeah, he provided the .mo too. I'll get an update out soon.

**Comment by michaelbeil** [comment]
:+1:
