### ISSUE TITLE
About custom the form ouput

### ISSUE THREAD

**Issue by giathinh910** [NateWr/restaurant-reservations#22]
Hi, I'm currently develope a restaurant theme and I'm trying to custom your reservation form. My design does not use the label for input field and placeholder is used instead. I looked for documentation to find any hook, however it seems that in the option there is no placeholder. So is there any way to add placeholder to the input field. Thank you.

**Comment by NateWr** [comment]
Hi @giathinh910,

Thanks for using my plugin in your theme. In this case, I'd recommend that you write your own callback functions to print the markup you want, then redefine each field's callback function to point to yours. Let me know if you need help with that.

If you want to make sure it's forward compatible with the Custom Fields addon that's coming out in a month or so, you should search through the `$fields` array for each of the callback functions defined in `template-functions.php`. These include `rtb_print_form_text_field`, `rtb_print_form_textarea_field`, `rtb_print_form_select_field`, `rtb_print_form_checkbox_field`, `rtb_print_form_radio_field`, and `rtb_print_form_confirm_field`.

A word of warning, though. `label` elements in forms are very important for users who require screen readers. If you're getting rid of them, I'd recommend you just hide them by wrapping them in a `screen-reader-text` class ([details here](https://make.wordpress.org/accessibility/2015/02/09/hiding-text-for-screen-readers-with-wordpress-core/)).

**Comment by giathinh910** [comment]
Thank you very very much. I found the hook rtb_booking_form_fields and I'm able to use my callback to custom the output. One more little question, I want to add another parametter to the call back, in this example I'd like to add tabindex value. However in the output my tab_index value is null. Where did I go wrong. Sorry, I'm just a newbie. Thanks very much for your helping.

My custom call back
```php
function my_rtb_print_form_text_field( $slug, $title, $value, $tab_index, $args = array() ) {
    $slug = esc_attr( $slug );
    $value = esc_attr( $value );
    $type = empty( $args['input_type'] ) ? 'text' : esc_attr( $args['input_type'] );
    $classes = isset( $args['classes'] ) ? $args['classes'] : array();
    ?>
    <div <?php echo rtb_print_element_class( $slug, $classes ); ?>>
        <?php echo rtb_print_form_error( $slug ); ?>
        <div class="form-group">
	        <label for="rtb-<?php echo $slug; ?>">
	            <span class="screen-reader-text">
	            	<?php echo $title; ?>
	            </span>
	        </label>
	        <input type="<?php echo $type; ?>" name="rtb-<?php echo $slug; ?>" id="rtb-<?php echo $slug; ?>" value="<?php echo $value; ?>" placeholder="<?php echo $title; ?>" tabindex="<?php echo $tab_index; ?>">
	    </div>
    </div>

    <?php
}
```
My custom field
```php
add_filter( 'rtb_booking_form_fields', 'my_custom_fields', 10, 2 );
function my_custom_fields( $fields, $request ) {

  $settings = new rtbSettings();

  $fields = array(

    // Reservation details fieldset
    'reservation' => array(
      'legend'  => __( 'Book a table', 'restaurant-reservations' ),
      'fields'  => array(
        'date'    => array(
          'title'     => __( 'Date', 'restaurant-reservations' ),
          'tab_index' => '4',
          'request_input' => empty( $request->request_date ) ? '' : $request->request_date,
          'callback'    => 'mauris_rtb_print_form_text_field',
          'required'    => true,
        )
      )
    ),

  );

  return $fields;
}
```

**Comment by NateWr** [comment]
The callback function is called [here](https://github.com/NateWr/restaurant-reservations/blob/master/includes/template-functions.php#L95), and as you'll see it references each of the array keys specifically in the callback function. So you can't just add a new one.

Instead, you should use the `callback_args` key to pass any custom arguments you have. Think of this like the `$args` array you can pass to `WP_Query`. You can tack on whatever args you want and then access them in the callback function.

**Comment by niyak2** [comment]
@NateWr   Hi im developing a reservation site with wordpress and im using that plugin but i want custom form for that plug in please help me to do that in your plugin , guide me the proper way to add additional fields .

**Comment by NateWr** [comment]
HI @niyak2, I'm not taking on any new custom work at the moment. Are you comfortable writing PHP code? If so, I outlined the steps required to add a custom field in [this support request](https://wordpress.org/support/topic/edit-form-label-and-add-input-fields?replies=13).

If you're not comfortable writing PHP code, I am developing an addon to add custom fields through the WordPress admin, which should be available some time in May. You can subscribe to my [mailing list](http://themeofthecrop.com/about/mailing-list/) if you want to be alerted when that's available.

**Comment by niyak2** [comment]
Hi @NateWr   thank you very sir for sharing that link , hope it will be helpfull while coding, i will try brother, Thank you very much for your kind reply

**Comment by niyak2** [comment]
hi i need to use that date field once  more any idea about that

**Comment by NateWr** [comment]
The plugin uses the [pickadate.js](http://amsul.ca/pickadate.js/) library. If you want to attach a date picker to a custom field that you've added, then you'll need to write some JavaScript to do that on the frontend.

**Comment by niyak2** [comment]
@NateWr Thank you for your kind help , successfully done everything

**Comment by niyak2** [comment]
hi @NateWr 

'enddate'		=> array(
						'title'			=> __( 'When does your event end?', 'restaurant-reservations' ),
						'request_input'	=> empty( $request->enddate ) ? '' : $request->enddate,
						'callback'		=> 'rtb_print_form_text_field',
						'required'		=> true,
					),
					'endtime'		=> array(
						'title'			=> __( 'Time', 'restaurant-reservations' ),
						'request_input'	=> empty( $request->endtime ) ? '' : $request->endtime,
						'callback'		=> 'rtb_print_form_text_field',
						'required'		=> true,
					),



This is my code for date and time in settings.class.php  so for this two if i need means where i need to give in the plugin folder itself , please give me a clue about this

**Comment by NateWr** [comment]
HI @niyak2, you shouldn't be editing the plugin files themselves. Instead, you should hook into the filters from another plugin. Have you seen the list of steps in [this support request](https://wordpress.org/support/topic/edit-form-label-and-add-input-fields?replies=13). It outlines each one of the hooks you need to use to add fields, and step 1 covers the modification of the `$fields` array.

You'll need to be familiar with WordPress's hooks system.
