### ISSUE TITLE
Date-picker default state to be unset?

### ISSUE THREAD

**Issue by tjoengnguyen** [NateWr/restaurant-reservations#24]
Hi Nate,

I'm not a PHP developer, thus quick question: how do I make it so the date-picker would be unset by default like the time-picker?

I look forward to hearing from you.
Cheers,
Tjoeng

**Comment by NateWr** [comment]
HI @tjoengnguyen, there's actually a setting for that. Go to `Bookings > Settings > Booking Schedule` and find the setting for **Date Pre-selection**. You can change that to leave the date empty in all cases.
