### ISSUE TITLE
Archive error

### ISSUE THREAD

**Issue by sacerro** [NateWr/restaurant-reservations#33]
PHP Warning: call_user_func() expects parameter 1 to be a valid callback, function ’’ not found or invalid function name in /var/www/vhosts/lifeofchaos.com/marcano.lifeofchaos.com/httpdocs/wp-content/plugins/restaurant-reservations/includes/template-functions.php on line 95, referer: http://marcano.lifeofchaos.com/prensa/

This error is thrown on archive page of custom post

**Comment by NateWr** [comment]
Hi @sacerro. This means that one of the callback functions for one of the fields is not properly defined. These are set in the `$fields` array [here](https://github.com/NateWr/restaurant-reservations/blob/master/includes/Settings.class.php#L763-L834).

My first guess would be that you're hooking into the filter to modify this array, and either not defining a callback or defining a callback function that doesn't exist.

If you're not modifying this array, then something else (a plugin or theme) is doing it. You'll want to deactivate plugins and switch to a default theme to determine the source of the problem.

**Comment by sacerro** [comment]
I'm only change some values from the original field
```
add_filter('rtb_booking_form_fields', 'custom_fields');
function custom_fields($fields, $request) {
	$fields['reservation']['legend'] = '';
	$fields['contact']['fields']['phone']['required'] = true;
	$fields['contact']['fields']['phone']['title'] = "Teléfono *";
	$fields['contact']['legend'] = '';
	$fields['contact']['fields']['add-message'] = '';
	$fields['contact']['fields']['message'] = '';
	$party_size = $fields['reservation']['fields']['party'];
	$fields['reservation']['fields']['party'] = '';
	$fields['contact']['fields']['party'] = $party_size;
	return $fields;
}
```

This means that I need to redefine callbacks for fields?

Thanks for all

**Comment by NateWr** [comment]
Yeah it won't work to do something like this:

```
$fields['contact']['fields']['add-message'] = '';
```

The array index will still be there, so the plugin will still try to fire off the associated callback and other details. Instead you need to unset the array key completely, like this:

```
unset( $fields['contact']['fields']['add-message']);
```

Also, I'd advise you to keep the fieldset legends. Rename them if you want, and then hide them with CSS. But fieldset legends are important for people who use assistive technologies like screen readers.

**Comment by sacerro** [comment]
I made the changes and now it's working, sorry for this ticket and thanks for you help.

**Comment by NateWr** [comment]
Great! Glad it's working for you.
