### ISSUE TITLE
Max reservation per day

### ISSUE THREAD

**Issue by sacerro** [NateWr/restaurant-reservations#34]
For example, your restaurant only can accept 20 pax (people) per hour. It's possible add this setting?

**Comment by NateWr** [comment]
Hi @sacerro, I don't plan to offer any capacity management in the base plugin. It gets complicated pretty fast depending on people's different needs. I've outlined some of those problems, and provided a couple of basic capacity management addons, in [this post](http://themeofthecrop.com/2015/05/19/basic-capacity-management-addons-for-restaurant-reservations/).

Though I do plan a more robust capacity management addon, I don't think it will be available soon. If you're a PHP coder, take a look at [this code](https://gist.github.com/NateWr/5af0297b1fb9d6d75ece#file-max-capacity-for-rtb-php-L95-L158) which checks daily capacity when validating a booking request. You'd obviously need to extend that to check the actual time of the bookings against the total capacity.

**Comment by sunsgs** [comment]
i tried your plugin extension but seems to be not working

**Comment by NateWr** [comment]
Hi @sunsgs, I'll need more information if I'm going to be able to help you.

**Comment by sunsgs** [comment]
hi @NateWr, i installed the plugin and activated it. That's it. If for today i book for 20 people, and the maximum capacity is 2, i can still book for today...should be not possible?

**Comment by NateWr** [comment]
If you set the max capacity to 2, it sounds like you modified it. Can you post your customized plugin code? I'll try it out on my end to see if I can reproduce the issue.

**Comment by sunsgs** [comment]
also if i try with (no mods) https://gist.github.com/NateWr/5af0297b1fb9d6d75ece#file-max-capacity-for-rtb-php-L95-L158 it not working..... i am able to book for 20 people in a day
