### ISSUE TITLE
{phone} doesn't work in email-subject

### ISSUE THREAD

**Issue by rousseauxy** [NateWr/restaurant-reservations#53]
When using {phone} in the email-subject it doesn't change the output to the actual phone-number, only displays the subject as this: "Uw reservatie van 30 april 2016 19:00 is in behandeling - {phone}"

**Comment by rousseauxy** [comment]
Question actually is, is there a way to make this work as it isn't default so :)

**Comment by NateWr** [comment]
Hi @rousseauxy,

You'll find all the template tags defined here:

https://github.com/NateWr/restaurant-reservations/blob/master/includes/Notification.class.php#L96

Only a few of them are available for the subject, but you can create more subject-specific template tags with the `rtb_notifications_email_subject_template_tags` filter here:

https://github.com/NateWr/restaurant-reservations/blob/master/includes/Notification.class.php#L96
