### ISSUE TITLE
Prevent same-day bookings

### ISSUE THREAD

**Issue by NateWr** [NateWr/restaurant-reservations#63]
The late bookings setting blocks bookings X hours in advance. However, it may be useful for some restaurants to block _same-day_ bookings.

In this case, all same day bookings would be rejected but a booking the following day, regardless of the current time, would be allowed.

Currently, if a 1-day setting is used, customers can't book for 2pm the following day if it's 3pm the current day.

**Comment by crysttn** [comment]
Nate, have you got enough requests for this enhancement? Are you planning to implement this feature soon? I'd be delighted if you are! :)
Cheers, Crys

**Comment by NateWr** [comment]
Hi Crys,

It's not a the top of my priority list. But it shouldn't be a very difficult one, so it might get picked up in a general update at some point.

Are you a developer able to write a little bit of JavaScript and load it on your site? If so, it wouldn't be hard for you to override the datepicker options to set the minimum date as 1 day ahead.

**Comment by NateWr** [comment]
Hi Crys, this has been implemented in 07afb4fafbfb63856957d15b8eecd32329d61913. It will be included in the next update, which I hope will go out later this week or next.

**Comment by crysttn** [comment]
Awesome!! Thanks a ton, Nate!
