### ISSUE TITLE
recatcha before form submission

### ISSUE THREAD

**Issue by amitabhaghosh197** [NateWr/restaurant-reservations#64]
It's a wonderful plugin. But I am just wanting to know how can I hook recaptcha validation  before submission of form

**Comment by NateWr** [comment]
Hi @amitabhaghosh197,

If you have an existing recaptcha solution, you can add and validate a field in the booking form using the hooks provided. An answer in the following support request gives you a quick outline of the hooks you'd need to use to add fields and perform validation on them:

https://wordpress.org/support/topic/edit-form-label-and-add-input-fields?replies=19
