### ISSUE TITLE
Location printed twice in details modal

### ISSUE THREAD

**Issue by NateWr** [NateWr/restaurant-reservations#74]
When multiple locations are in use, the location appears twice in the details column popup. When a single location is being viewed, the data is still printed in the modal. And the location column can't be manipulated with the column display control.
- [x] Don't double-print the location details in the modal 
- [x] Make the location column show/hide option work (Implemented as part of a75ebf17223f39fac60ca411acb20005bd15438a )

**Comment by buddybergh** [comment]
Any updates available?

**Comment by NateWr** [comment]
No not yet. Issues labeled `bug` usually get sorted out in time for the next release, but I don't commit to a regular release schedule.

**Comment by NateWr** [comment]
@buddybergh A fix has been committed and will go out with the next update. I'm expecting that to be this week or next.
