### ISSUE TITLE
Add HTML5 required attribute to the form fields

### ISSUE THREAD

**Issue by jadebermas** [NateWr/restaurant-reservations#79]
Hi there,

As you mentioned on your response from the forum, I am posting this issue here.

I am currently building a restaurant website and it would be good to have this feature implemented since a lot of modern browsers if not all supports the required attribute.

Thanks for this plugin. :)

**Comment by NateWr** [comment]
Thanks @jadebermas, definitely on the todo list. :+1:

**Comment by NateWr** [comment]
Hi @jadebermas, this was added in 356937d2415b0c698fe01bda2903aac6dd9dfbe0 and will go out with the next version.
