### ISSUE TITLE
Edit in admin a reservation in the past. error rtb-date

### ISSUE THREAD

**Issue by jdwisse** [NateWr/restaurant-reservations#80]
if you edit a reservation in the past in de admin

pickadate -> min gives the error. It will gives the current date.

rtb-date needs to give the date of the edit reservation

**Comment by NateWr** [comment]
Thanks @jdwisse, I'll flag this up for improving in a future version. I've never really had the request to do this before but seems like an obvious thing to allow in the backend.

**Comment by NateWr** [comment]
The booking date and time pickers in admin should allow booking at any time as well.

**Comment by jdwisse** [comment]
Yes i think it is good idea. An option to only show opening hours or give them another appearance would be great. It can be done by adding a class. For [example](https://translate.google.com/translate?hl=en&sl=nl&tl=en&u=https%3A%2F%2Fwww.huson.nl%2Freserveren%2F), i hide the disable option time slot by class in the front-end.

**Comment by NateWr** [comment]
@jdwisse This has been implemented and will go out with the next update, hopefully this week or next.

**Comment by jdwisse** [comment]
tnx in advanced

Met vriendelijke groet,

Jeroen Wisse

2016-12-01 14:55 GMT+01:00 Nate Wright <notifications@github.com>:
