### ISSUE TITLE
Counting reservations

### ISSUE THREAD

**Issue by buddybergh** [NateWr/restaurant-reservations#84]
I have two locations. The first location "leiden" works fine. On the second location "voorburg" the system won't count the amount of reservations. Its not possible to use the pagination (1 2 3 4) cause its hidden. Works only on the first location "leiden". 

Its not possible to restart with a fresh database. I need to backup all the reservations and import them. Probably the same problem will occur.

**wp_terms:**
Geen categorie geen-categorie 0 1
Main menu main-menu 0 2
Leiden leiden 0 8
Voorburg voorburg 0 9

**wp_postmeta:**
- meta_id 
- post_id 
- meta_key 
- meta_value

**1 reservation for Leiden (works great)**
- 8399 
- rtb 
- a:4: {s:5:"party";i:17;s:5:"email";s:20:"test@hotmail.com";s:5:"phone";s:10:"06000000";s:15:"date_submission";i:1478019635;}
- 11269

**1 reservation for Voorburg (won't count)**
- 9288
- rtb
- a:4:{s:5:"party";i:10;s:5:"email";s:29:"test@hotmail.com";s:5:"phone";s:10:"06000000";s:15:"date_submission";i:1479234317;}
- 12775

**Comment by NateWr** [comment]
Hi @buddybergh,

Are you able to provide some screenshots? I've just tested locally and I get correct counts of the bookings per location and I'm able to navigate to subsequent pages when necessary.

When multiple locations are active, the pagination at the top of the list is replaced with the location switcher. But you should still be able to visit subsequent pages using the controls at the bottom of the list.

**Comment by buddybergh** [comment]
![leiden](https://cloud.githubusercontent.com/assets/22390003/20345090/d50eea2a-abf5-11e6-8667-878517b1965d.jpg)
![voorburg](https://cloud.githubusercontent.com/assets/22390003/20345089/d50cf0a8-abf5-11e6-9ac4-5d43837609c3.jpg)

**Comment by buddybergh** [comment]
If i add a new location. it doesn't work neither (doesn't count)

**Comment by NateWr** [comment]
@buddybergh When locations are active, the pagination only appears at the bottom right, like this.

![selection_056](https://cloud.githubusercontent.com/assets/2306629/20353303/42d628d6-ac12-11e6-9f47-a1c1be3e946d.png)

Does it not appear for you there?

**Comment by buddybergh** [comment]
Only on my first location "Leiden" because the counting works. On my second location "voorburg" it doenst appear there. See attachment
![overzicht](https://cloud.githubusercontent.com/assets/22390003/20387716/c1997e48-acc1-11e6-9911-78b1af82deef.jpg)

**Comment by NateWr** [comment]
Hmm, I can't reproduce the issue on my end. I'd recommend checking that all the plugins are up-to-date, then trying to deactivate all other plugins and switch to a default theme to see if the problem persists.

Sorry I don't have any other ideas for you. The code which handles those counts is here:

https://github.com/NateWr/restaurant-reservations/blob/master/includes/WP_List_Table.BookingsTable.class.php#L909
