### ISSUE TITLE
Pager Builder and restaurant reservations

### ISSUE THREAD

**Issue by wstephan** [NateWr/restaurant-reservations#98]
Hi
first, thank's vey much for this great plugin. I use it together which page builder (https://srd.wordpress.org/plugins/siteorigin-panels/). It worked great until yesterday. Page Builder updated the Plugin and now, i see only an empty Site, when i include the Widget into Page Builder.
Sorry, i don't know if the problem because Pager Builder or Restaurant Reservations Plugin. But Page Builder is very popular and i think, it's good to know, that there's a problem at the moment.

I'm not realy experienced in coding plugins. But when you need some information, feel free to ask. I try to help you as much as possible...

Best regards
Steve

**Comment by NateWr** [comment]
Hi Steve,

Are you the one from the WordPress.org support forum here:

https://wordpress.org/support/topic/cant-use-within-pagebuilder/#post-8836803
